# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will build, test, sign and package a WPF or Windows Forms desktop application
# built on .NET Core.
# To learn how to migrate your existing application to .NET Core,
# refer to https://docs.microsoft.com/en-us/dotnet/desktop-wpf/migration/convert-project-from-net-framework
#
# To configure this workflow:
#
# 1. Configure environment variables
# GitHub sets default environment variables for every workflow run.
# Replace the variables relative to your project in the "env" section below.
#
# 2. Signing
# Generate a signing certificate in the Windows Application
# Packaging Project or add an existing signing certificate to the project.
# Next, use PowerShell to encode the .pfx file using Base64 encoding
# by running the following Powershell script to generate the output string:
#
# $pfx_cert = Get-Content '.\SigningCertificate.pfx' -Encoding Byte
# [System.Convert]::ToBase64String($pfx_cert) | Out-File 'SigningCertificate_Encoded.txt'
#
# Open the output file, SigningCertificate_Encoded.txt, and copy the
# string inside. Then, add the string to the repo as a GitHub secret
# and name it "Base64_Encoded_Pfx."
# For more information on how to configure your signing certificate for
# this workflow, refer to https://github.com/microsoft/github-actions-for-desktop-apps#signing
#
# Finally, add the signing certificate password to the repo as a secret and name it "Pfx_Key".
# See "Build the Windows Application Packaging project" below to see how the secret is used.
#
# For more information on GitHub Actions, refer to https://github.com/features/actions
# For a complete CI/CD sample to get started with GitHub Action workflows for Desktop Applications,
# refer to https://github.com/microsoft/github-actions-for-desktop-apps

name: Build and Package Project


on:
  push:
    tags: [ '*' ]

jobs:
  # create-tag:
  #   if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/master')
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #   outputs:
  #     new_tag: ${{ steps.create_tag.outputs.new_tag }}
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - name: Bump version and create tag
  #       id: create_tag
  #       uses: anothrNick/github-tag-action@1.65.0
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         TAG_PREFIX: ''
  #         DEFAULT_BUMP: patch
  get_version:
    # if: always() && ( needs.create-tag.result == 'success' || startsWith(github.ref, 'refs/tags/') )
    # needs: [create-tag]
    runs-on: ubuntu-latest
    outputs:
      rel_ver: ${{ steps.set_versions.outputs.REL_VER }}
      rel_env: ${{ steps.set_versions.outputs.REL_ENV }}
    steps:
    - name: Set Version Env
      id: set_versions
      shell: bash
      run: |
        VERSION=${{github.ref_name}}
        if [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+-[a-zA-Z0-9]+\.[0-9]+$ ]]; then
          echo "Detected prerelease version: $VERSION"
          ENVIRONMENT="PRE"
        elif [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Detected release version: $VERSION"
          ENVIRONMENT="RELEASE"
        else
          echo "ERROR: Not a valid version format." >&2
          exit 1
        fi
        echo "REL_VER=$VERSION" >> $GITHUB_OUTPUT
        echo "REL_ENV=$ENVIRONMENT" >> $GITHUB_OUTPUT
  build:
    if: |
      needs.get_version.result == 'success'
    needs: [get_version]
    strategy:
      matrix:
        rid: [win-x64, win-x86]  # Add other RIDs as needed. Refer to
                                    # https://docs.microsoft.com/en-us/dotnet/core/rid-catalog for a list of RIDs.

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: VEIOfflineClient.slnx                         # Replace with your solution name, i.e. MyWpfApp.sln.
      UI_Project_Path: VEIOfflineClient\VEIOfflineClient.csproj    # Replace with the Wap project directory relative to the solution, i.e. MyWpfApp.Package.
      DevExpress_License: ${{ secrets.DEVEXPRESS_LICENSE_KEY }}
      REL_VER: ${{ needs.get_version.outputs.rel_ver }}
      REL_ENV: ${{ needs.get_version.outputs.rel_env }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    

    # Remove the pfx
    - name: Publish
      run: >
        dotnet publish ${{ env.UI_Project_Path }} -c Release -r ${{ matrix.rid }} 
        -f net8.0-windows --self-contained -p:PublishReadyToRun=${{ env.REL_ENV == 'RELEASE' && 'true' || 'false' }}
        -o "${{ github.workspace }}\publish" -p:Version=${{ env.REL_VER }}
    
    - name: Update appSettings.json
      shell: pwsh
      run: |
        $path = "${{ github.workspace }}\publish\appsettings.json"
        $json = Get-Content $path | ConvertFrom-Json

        $json.Environment.Stage = "${{ env.REL_ENV }}"
        $json.Environment.UpdatePath = "https://oss.jcdev.cc/vei/offline/${{ matrix.rid }}/${{ env.REL_ENV }}/"
        $json | ConvertTo-Json -Depth 10 | Set-Content $path -Encoding UTF8
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.rid }}-build
        path: ${{ github.workspace }}/publish

  deploy:
    if: |
      needs.build.result == 'success'
    needs: [build, get_version]
    runs-on: windows-latest
    concurrency:
      group: 'deploy-${{ matrix.rid }}-${{ needs.get_version.outputs.rel_env }}'
      cancel-in-progress: false
    strategy:
      max-parallel: 1
      matrix:
        rid: [win-x64, win-x86]  # Add other RIDs as needed. Refer to
                                    # https://docs.microsoft.com/en-us/dotnet/core/rid-catalog for a list of RIDs.
    env:
      Project_Name: VEIOfflineClient                             # Replace with your project name, i.e. MyWpfApp.
      REL_VER: ${{ needs.get_version.outputs.rel_ver }}
      REL_ENV: ${{ needs.get_version.outputs.rel_env }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Create Deployment Tag
      run: echo "Deployed version ${{ env.REL_VER }}"

    - name: Setup S3 SecretKey
      run: |
        aws configure set aws_access_key_id ${{secrets.CLOUD_KEY}}
        aws configure set aws_secret_access_key ${{secrets.CLOUD_SECRET}}
        aws configure set addressing_style virtual

    - name: Install Velopack CLI
      run: dotnet tool install -g vpk
    - name: Download Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ matrix.rid }}-build
        path: ${{ github.workspace }}/publish

    - name: Download Remote Package
      continue-on-error: true
      run: >
        vpk download s3 -o "${{github.workspace}}\release" --keyId ${{secrets.CLOUD_KEY}} --secret ${{secrets.CLOUD_SECRET}} 
        --endpoint https://cos.ap-tokyo.myqcloud.com --bucket vei-1252567852 --prefix vei/offline/${{ matrix.rid }}/${{ env.REL_ENV }}
        --disablePathStyle

    
    - name: Create Package
      run: >
        vpk pack -o "${{github.workspace}}\release" --runtime ${{ matrix.rid }} --packId ${{ env.Project_Name }}_${{ env.REL_ENV }}
        --packVersion ${{ env.REL_VER }} --packDir "${{ github.workspace }}\publish" --packAuthors "万华物装" --packTitle "VEI单机版(${{ env.REL_ENV == 'RELEASE' && '正式版' || '测试版' }})"
        -e ${{ env.Project_Name }}.exe
    
    - name: Upload Package
      run: >
        vpk upload s3 -o "${{github.workspace}}\release" --keyId ${{secrets.CLOUD_KEY}} --secret ${{secrets.CLOUD_SECRET}}
        --endpoint https://cos.ap-tokyo.myqcloud.com --bucket vei-1252567852 --prefix vei/offline/${{ matrix.rid }}/${{ env.REL_ENV }}
        --disablePathStyle
    - name: Update update.json to S3
      run: |
        aws s3 cp "publish/version.json" s3://vei/offline/${{ matrix.rid }}/${{ env.REL_ENV }}/version.json --endpoint-url https://vei-1252567852.cos.ap-tokyo.myqcloud.com --acl public-read
